<?php

namespace JE\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function queryAll()
    {
        return $this->createQueryBuilder('u')
            ->orderBy('u.firstName, u.lastName');
    }
}
