imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - ':Form:form_div_layout.html.twig'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    read_from:      "%kernel.root_dir%/../www"
    filters:
        cssrewrite: ~
        lessphp:
            apply_to: "\.less$"
            file: %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php
            formatter: "compressed"
            preserve_comments: false
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        entity_managers:
            default:
                auto_mapping: true
                dql:
                    numeric_functions:
                        year: JE\FinancesBundle\DQL\Year
                        month: JE\FinancesBundle\DQL\Month
                        max: JE\FinancesBundle\DQL\Max
                        min: JE\FinancesBundle\DQL\Min
                        sum: JE\FinancesBundle\DQL\Sum

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

fos_user:
    db_driver:     orm
    firewall_name: main
    user_class:    JE\UserBundle\Entity\User
    group:
        group_class: JE\UserBundle\Entity\Group

stof_doctrine_extensions:
    uploadable:
        default_file_path:       %kernel.root_dir%/../www/uploads
        mime_type_guesser_class: Stof\DoctrineExtensionsBundle\Uploadable\MimeTypeGuesserAdapter
        default_file_info_class: Stof\DoctrineExtensionsBundle\Uploadable\UploadedFileInfo
        validate_writable_directory: false
    orm:
        default:
            sluggable: true
            timestampable: true
            blameable: true
            uploadable: true
            sortable: true

ivory_ck_editor:
    default_config: main
    configs:
        main:
            toolbar: "toolbar_basic"
    toolbars:
        configs:
            toolbar_basic: [ "@clipboard", "@editing" , "/", "@basicstyles", "@links", "@paragraph" , "/", '@styles', '@tools' ]
        items:
            document : [ 'Source','-','Save','NewPage','DocProps','Preview','Print','-','Templates' ]
            clipboard : [ 'Cut','Copy','Paste','PasteText','PasteFromWord','-','Undo','Redo' ]
            editing : [ 'Find','Replace','-','SelectAll','-','SpellChecker', 'Scayt' ]
            forms : [ 'Form', 'Checkbox', 'Radio', 'TextField', 'Textarea', 'Select', 'Button', 'ImageButton', 'HiddenField' ]

            basicstyles : [ 'Bold','Italic','Underline','Strike','Subscript','Superscript','-','RemoveFormat' ]
            paragraph : [ 'NumberedList','BulletedList','-','Blockquote','-','JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock' ]
            links: [ 'Link','Unlink','Anchor' ]
            insert : [ 'Image','Flash','Table','HorizontalRule','Smiley','SpecialChar','PageBreak' ]

            styles : [ 'Format','FontSize' ]
            colors : [ 'TextColor','BGColor' ]
            tools : [ 'Source', 'Maximize' ]

jms_di_extra:
    automatic_controller_injections:
        properties:
            request: @request
            em: @doctrine.orm.entity_manager
            um: @fos_user.user_manager
            gm: @fos_user.group_manager
            paginator: @knp_paginator
            uploadableManager: @stof_doctrine_extensions.uploadable.manager
            mailer: @mailer
            session: @session
            dispatcher: @event_dispatcher

jms_security_extra:
    expressions: true

knp_paginator:
    page_range: 5
    default_options:
        page_name: page
    template:
        pagination: ::pagination.html.twig
        sortable:   ::sortable.html.twig