je_stat:
    resource: "@JEStatBundle/Resources/config/routing.yml"
    prefix:   /stats

je_finances:
    resource: "@JEFinancesBundle/Resources/config/routing.yml"
    prefix:   /finances

je_user:
    resource: "@JEUserBundle/Resources/config/routing.yml"
    prefix:   /team

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile