security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_USERS:         [ROLE_USERS_VIEW, ROLE_USERS_ADD, ROLE_USERS_EDIT, ROLE_USERS_REMOVE]
        ROLE_GROUP:         [ROLE_GROUP_VIEW, ROLE_GROUP_ADD, ROLE_GROUP_EDIT, ROLE_GROUP_REMOVE]
        ROLE_TREZ:          [ROLE_TREZ_VIEW, ROLE_TREZ_ADD, ROLE_TREZ_EDIT, ROLE_TREZ_REMOVE]
        ROLE_ADMIN:         [ROLE_USERS, ROLE_GROUP, ROLE_TREZ]
        ROLE_SUPER_ADMIN:   [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/(login|login_check)
            anonymous: ~
            context: main_firewall
            form_login:
                csrf_provider: form.csrf_provider
                login_path: fos_user_security_login
                check_path: fos_user_security_check

        main:
            pattern: ^/
            anonymous: false
            context: main_firewall
            provider: fos_userbundle
            form_login:
                csrf_provider: form.csrf_provider
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path: /
                remember_me: true
            logout:
                path: fos_user_security_logout
                target: /
                invalidate_session: false
            remember_me:
                key: %secret%
                name: SeSouvenirDeMoi
                lifetime: 3600

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
