je_user_groups:
    pattern:  /
    defaults: { _controller: JEUserBundle:Group:index }

je_user_groups_new:
    pattern:  /new
    defaults: { _controller: JEUserBundle:Group:new }

je_user_groups_edit:
    pattern:  /{id}/edit
    defaults: { _controller: JEUserBundle:Group:edit }
    requirements:
        id: \d+