je_user_users:
    pattern:  /{page}
    defaults: { _controller: JEUserBundle:User:index, page: 1 }
    requirements:
        page: \d+

je_user_users_new:
    pattern:  /new
    defaults: { _controller: JEUserBundle:User:new }

je_user_users_edit:
    pattern:  /{id}/edit
    defaults: { _controller: JEUserBundle:User:edit }
    requirements:
        id: \d+

je_user_users_profile:
    pattern:  /{id}/profile
    defaults: { _controller: JEUserBundle:User:profile }
    requirements:
        id: \d+