je_finances_bv:
    pattern:  /{page}/{sort}/{direction}
    defaults: { _controller: JEFinancesBundle:PaymentSlip:index, page: 1, sort: s.createdAt, direction: desc }
    requirements:
        page: \d+
        sort: s\.[^/]+
        direction: asc|desc

je_finances_bv_new:
    pattern:  /new
    defaults: { _controller: JEFinancesBundle:PaymentSlip:new }

je_finances_bv_edit:
    pattern:  /{bv}/edit
    defaults: { _controller: JEFinancesBundle:PaymentSlip:edit }
    requirements:
        bv: BV\d+